### ISSUE TITLE
tagslam_node execution error

### ISSUE THREAD

**Issue by BBO-repo** [berndpfrommer/tagslam_root#1]
Hi Bernd,
Since last repo update I have an execution error with tagslam_node whereas the code cloned one month ago work nicely. The execution error is joined cf print screen.
![image](https://user-images.githubusercontent.com/17410064/62352010-62e3b700-b507-11e9-8659-5e96ee932083.png)

**Comment by berndpfrommer** [comment]
You get this error if you don't do

catkin config -DCMAKE_BUILD_TYPE=Release

Closing issue after conferring with @BBO-repo on google groups

https://groups.google.com/forum/#!topic/tagslam/n51UbpQTMfE
