### ISSUE TITLE
Unable to get submodules

### ISSUE THREAD

**Issue by yanhuicm** [berndpfrommer/tagslam_root#10]
Hi there, I'm unable to clone the submodules for this project. I'm receiving errors for all the submodules like the below.
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:berndpfrommer/tagslam_web.git' into submodule path '/home/user/tagslam_root/src/tagslam_web' failed
Failed to clone 'src/tagslam_web'. Retry scheduled
Cloning into '/home/user/tagslam_root/src/apriltag'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```
Have the public keys gone expired or something? Thanks in advance!

**Comment by berndpfrommer** [comment]
I just tried it and the recursive clone works fine for me.
To me this looks like a problem with the ssh keys you are using for github access. Make sure they are present on the machine you are using, they are unlocked ("ssh-add"), and properly deposited with github:
https://jdblischak.github.io/2014-09-18-chicago/novice/git/05-sshkeys.html#:~:text=Login%20to%20github.com%20and,hit%20Add%20key%20to%20save.

**Comment by yanhuicm** [comment]
The SSH method works! Thanks for your help!
