### ISSUE TITLE
No packages to be built.

### ISSUE THREAD

**Issue by ShidMoosavi** [berndpfrommer/tagslam_root#13]
when I'm using the `catkin build` as yous see in the attachment I receive an error that `No packages were found in the source space '/home/sina/tagslam_root/src'` 
![Screenshot from 2022-06-14 13-24-49](https://user-images.githubusercontent.com/91393627/173639672-1b40744f-d615-47bf-9849-6c68a522026d.png)

**Comment by berndpfrommer** [comment]
Is ROS installed correctly? The error ``Unable to find ... empy .. or em`` does not look like it is related to tagslam.

**Comment by berndpfrommer** [comment]
Closed due to no response.
