### ISSUE TITLE
fail to execute the quick test

### ISSUE THREAD

**Issue by SeanGuoXuan** [berndpfrommer/tagslam_root#2]
When I execute the quick test:
roslaunch tagslam tagslam.launch bag:=`rospack find tagslam`/example/example.bag

I got the following exception:

tagslam_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.

Any idea how to fix this bug?
Many thxs in advance.

**Comment by berndpfrommer** [comment]
Could you please say what OS and what ROS version you are building on?

Also, try this:
catkin clean
catkin config -DCMAKE_BUILD_TYPE=Release
catkin build

**Comment by SeanGuoXuan** [comment]
OS: Ubuntu 16.04 LTX
ROS: kinetic
rosversion: 1.12.14

After clean workspace and rebuild with build type 'release', it is working normally. However, if I change to the following command:
catkin config -DCMAKE_BUILD_TYPE=Debug
catkin build
It builds successfully. But, I got runtime exception similar to previous one.

process[tagslam-1]: started with pid [15801]
[ INFO] [1570680534.246251174]: added body grasp_lab with 1 tags
[ INFO] [1570680534.246386914]: added body rig with 0 tags
[ INFO] [1570680534.284343985]: found 1 cameras
[ INFO] [1570680534.287270014]: camera cam0 has known pose!
[ INFO] [1570680534.287652528]: no distance measurements found!
[ INFO] [1570680534.287718907]: no coordinate measurements found!
[ INFO] [1570680534.287777350]: no plane measurements found!
[ INFO] [1570680535.672127270]: reading from bag: /home/sean/sean/tagslam_ws/src/tagslam/example/example.bag
[ INFO] [1570680535.826648430]: number of tag   topics: 1
[ INFO] [1570680535.826720314]: number of image topics: 0
[ INFO] [1570680535.826747257]: number of odom  topics: 0
[ INFO] [1570680535.851369851]: frame 0 cam0 sees tags: 
[ INFO] [1570680535.851928685]: frame 1 cam0 sees tags: 
[ INFO] [1570680535.858006979]: frame 2 cam0 sees tags: 
[ INFO] [1570680535.858387014]: frame 3 cam0 sees tags: 
[ INFO] [1570680535.867813444]: new tag 3 attached to grasp_lab
[ INFO] [1570680535.868379538]: frame 4 cam0 sees tags:  3
[ INFO] [1570680535.870592696]: sum of subgraph err: 0, full graph error: 0
[ INFO] [1570680535.870844181]: graph after update: opt fac: 4 unopt fac: 1 opt vals: 4 unopt vals: 2
[ INFO] [1570680535.871410680]: frame 5 cam0 sees tags:  3 0
tagslam_node: /usr/include/gtsam/3rdparty/Eigen/Eigen/src/Core/CommaInitializer.h:66: Eigen::CommaInitializer<MatrixType>& Eigen::CommaInitializer<MatrixType>::operator,(const Scalar&) [with XprType = Eigen::Matrix<double, 2, 4>; Eigen::CommaInitializer<MatrixType>::Scalar = double]: Assertion `m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"' failed.
tagslam_node: /usr/include/gtsam/3rdparty/Eigen/Eigen/src/Core/CommaInitializer.h:66: Eigen::CommaInitializer<MatrixType>& Eigen::CommaInitializer<MatrixType>::operator,(const Scalar&) [with XprType = Eigen::Matrix<double, 2, 4>; Eigen::CommaInitializer<MatrixType>::Scalar = double]: Assertion `m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"' failed.
tagslam_node: /usr/include/gtsam/3rdparty/Eigen/Eigen/src/Core/CommaInitializer.h:66: Eigen::CommaInitializer<MatrixType>& Eigen::CommaInitializer<MatrixType>::operator,(const Scalar&) [with XprType = Eigen::Matrix<double, 2, 4>; Eigen::CommaInitializer<MatrixType>::Scalar = double]: Assertion `m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"' failed.

Any idea why?

**Comment by berndpfrommer** [comment]
Very good you opened this issue. I found a bunch of bugs when running under Debug, one of them serious (radtan distortion ignoring coefficients k3-k6).
I pushed the fixes into the master branch. Can you test and see if you still have issues?

**Comment by SeanGuoXuan** [comment]
Thanks. This bug is fixed and now I am be able to execute the sample under debug mode.  The first error I think I had issue with eigen package or corrupted environment. It is no longer issue after I resetup the environment. 

One thing I think you should be aware that you have repositories "tagslam_root" and "tagslam". It seems the bug fix is submitted to "tagslam" but not "tagslam_root".  I need to merge manually to fix.
