### ISSUE TITLE
Error with submodule tagslam_web

### ISSUE THREAD

**Issue by urbste** [berndpfrommer/tagslam_root#4]
Hi,

I wanted to try out tagslam, however there is an error with tagslam_web when cloning recusively:
fatal: Referenz ist kein "Tree"-Objekt: 587666c625f4531b33df4074e406c33b00e0dafd
Konnte '587666c625f4531b33df4074e406c33b00e0dafd' in Submodul-Pfad 'src/tagslam_web' nicht auschecken.

If I use your last commit ae765eb it works:
git clone https://github.com/berndpfrommer/tagslam_root.git
git checkout ae765eb 
git submodule init
git submodule update

Regards
Steffen

**Comment by berndpfrommer** [comment]
I think I didn't push one of the sub repos.
Thanks for pointing this out!
Will fix it shortly..

**Comment by berndpfrommer** [comment]
Indeed, tagslam_web had not been pushed. That has been fixed and tested now.
