### ISSUE TITLE
How can we get the error metrics /visualize the re-projection error for camera calibration?

### ISSUE THREAD

**Issue by OOF-dura** [berndpfrommer/tagslam_root#8]
I just calibrate cameras using TAGSLAM! Thank you very much for your great work!
My question is how can we get the error metrics /visualize the re-projection error for camera calibration?
Thank you very much!

**Comment by berndpfrommer** [comment]
Sorry, but TagSLAM does not output the projection errors as a full blown calibration package would.
After the optimizer has run you will find a sorted list of errors in ~/.ros/error_map.txt. It will have the square error and the factor from which that error arises. So at least you can spot some outliers there and potentially mask them out. The error should be 0.5 * (pixel_error/pixel_noise_sigma)^2, i.e. the errors in error_map.txt will depend on the width of the gaussian noise that you have in your tagslam input file. Error_map.txt this will give you an idea of the magnitude of error, but not the projection residuals as e.g. Kalibr and other packages report it.
